### ISSUE TITLE
Add step types

### ISSUE THREAD

**Issue by pkosiec** [pkosiec/terminer#14]
- [ ] Define generic step types
- [ ] Add ability to select, which steps should be executed, and which not

**Example**

Imagine that user wants to install Fish shell with all plugins, but (s)he doesn't want to set is as default shell. He could be able to exclude somehow the last step, which has type like "SET_DEFAULT" defined.

```yaml
- name: "Set as default shell"
  type: OPTIONAL
  steps:
  - cmd: "chsh -s $(which fish)"
    rollback: "chsh -s $(which bash)"
```

There could be for example a toggle `--ignore-optional` to ignore optional steps.
